version: '3'

services:
  litee-app-db:
    image: postgres:latest
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 543210
      POSTGRES_DB: litee-app
  litee-app-test-db:
    image: postgres:latest
    ports:
      - 4321:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 43210
      POSTGRES_DB: litee-app-test
